version: "3.9"

networks:
  hrs-lab:
    driver: bridge

services:
  backend:
    build: ./backend-app
    container_name: backend-app
    command: >
      gunicorn app:app --bind 0.0.0.0:8000 --workers 1 --threads 1 --keep-alive 60 --limit-request-line 0 --limit-request-field_size 0 --limit-request-fields 100

    expose:
      - "8000"
    networks:
      - hrs-lab
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 10s
      timeout: 3s
      retries: 3

  nginx:
    depends_on:
      backend:
        condition: service_healthy
    image: nginx:1.23
    container_name: nginx-proxy
    ports:
      - "8080:80"

    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    networks:
      - hrs-lab
